[package]
name = "rust-rocket"
version = "0.1.0"
authors = ["Richard Tjerngren <rtjerngren@spotify.com>"]
edition = "2018"

[dependencies]
gotham = "0.3.0"
hyper = "0.12.31"
futures = "0.1.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mime = "0.3.13"
